// <auto-generated />
using System;
using CookbookApp.Model.CookbookApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookbookApp.Model.Migrations
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.Recipe", b =>
                {
                    b.Property<string>("RecipeNameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedTagsTagName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSaved")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SavedRecipe")
                        .HasColumnType("BLOB");

                    b.HasKey("RecipeNameId");

                    b.HasIndex("AppliedTagsTagName");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.Tags", b =>
                {
                    b.Property<string>("TagName")
                        .HasColumnType("TEXT");

                    b.HasKey("TagName");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.Recipe", b =>
                {
                    b.HasOne("CookbookApp.Model.CookbookApp.Model.Tags", "AppliedTags")
                        .WithMany()
                        .HasForeignKey("AppliedTagsTagName");
                });
#pragma warning restore 612, 618
        }
    }
}
